<?php

/**
 * SITEURL
 */
define('SITEURL', '2dtrussdeflection/');

/**
 * Young modulus
 * assumed same to all members
 */
define('E', '30000');

/**
 * Area of cross-section for each member
 * assumed same to all members
 */
define('A', '10');

/**
 * magnifying factor of displacements
 */
define('MAGNIFICATION_FACTOR', 20.0);

/**
 * length amplification factor for unit conversion
 */
define('LENGTH_FACTOR', 1.0);

/**
 * magnifying factor in general
 */
define('GENERAL_MAGNIFICATION_FACTOR', 50.0);

?>
